catalog:
  vite-plus: ^0.1.20

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "react-email"
  - "@react-email/render"
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"

onlyBuiltDependencies:
  - '@google/genai'
  - "@infisical/cli"
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - core-js
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
