ignoredBuiltDependencies:
  - libpq

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@biomejs/biome"
  - "@biomejs/*"
  - "react-email"
  - "@react-email/render"

onlyBuiltDependencies:
  - "@infisical/cli"
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - core-js
  - esbuild
  - msw
  - prisma
  - sharp
