minimumReleaseAge: 1440
minimumReleaseAgeExclude:

onlyBuiltDependencies:
  - "@google/genai"
  - "@infisical/cli"
  - "@prisma/client"
  - "@prisma/engines"
  - "@sentry/cli"
  - libpq
  - core-js
  - esbuild
  - msw
  - prisma
  - protobufjs
  - sharp

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
