import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Row,
  Section,
  Tailwind,
  Text,
  pixelBasedPreset,
} from "@react-email/components";
import Link from "~/components/email/Link";

/**
 * EmailLayout is a component that wraps the email content and provides a consistent layout.
 * It is used to ensure that all emails have the same layout and consistent styling.
 *
 * @param children - The content of the email.
 * @param preview - The preview text of the email. If not provided, the subject will be used.
 * @param subject - The subject of the email.
 * @param unsubscribeURL - The URL to unsubscribe from all emails.
 * @returns The HTML email.
 */
export default function EmailLayout({
  children,
  domain,
  preview,
  subject,
  unsubscribeURL,
}: {
  children: React.ReactNode;
  domain?: string;
  preview?: string;
  subject: string;
  unsubscribeURL?: string | false;
}) {
  return (
    <Html>
      <Head />
      <Preview>{preview ?? subject}</Preview>
      <Tailwind
        config={{
          presets: [pixelBasedPreset],
          theme: {
            extend: {
              colors: {
                primary: "#4f46e5",
                text: "#374151",
                dark: "#1f2937",
                light: "#6b7280",
                background: "#f6f9fc",
                white: "#ffffff",
                highlightBg: "#f3f4f6",
                border: "#e5e7eb",
                borderLight: "#f0f0f0",
              },
            },
          },
        }}
      >
        <Body className="bg-background font-sans text-text">
          <Container className="mx-auto my-40px max-w-600px bg-white p-4">
            <Header domain={domain} subject={subject} />
            {children}
            <Footer unsubscribeURL={unsubscribeURL} />
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}

function Header({ domain, subject }: { domain?: string; subject: string }) {
  const logoSrc = new URL(
    "/icon-192.png",
    import.meta.env.VITE_APP_URL,
  ).toString();

  if (domain) {
    return (
      <Section className="mb-6 border-border border-b pb-6">
        <Row>
          <Column style={{ verticalAlign: "middle" }}>
            <Row>
              <Column style={{ width: "44px", verticalAlign: "middle" }}>
                <Img alt="cite.me.in" height={36} src={logoSrc} width={36} />
              </Column>
              <Column style={{ verticalAlign: "middle" }}>
                <Link
                  href={new URL(
                    `/site/${domain}`,
                    import.meta.env.VITE_APP_URL,
                  ).toString()}
                >
                  <Text className="m-0 font-bold text-2xl text-dark leading-tight">
                    {domain}
                  </Text>
                  <Text className="m-0 mt-4px text-light text-sm">
                    {subject}
                  </Text>
                </Link>
              </Column>
            </Row>
          </Column>
          <Column
            className="text-right"
            style={{ verticalAlign: "middle", whiteSpace: "nowrap" }}
          >
            <Text className="m-0 text-light text-sm">
              ⚡ Generated by{" "}
              <Link href={import.meta.env.VITE_APP_URL}>
                <strong className="text-dark">cite.me.in</strong>
              </Link>
            </Text>
          </Column>
        </Row>
      </Section>
    );
  }

  return (
    <Section>
      <Heading className="my-6 flex items-center justify-center gap-2 whitespace-nowrap text-center">
        <Img alt="cite.me.in" height={32} src={logoSrc} width={32} />
        <span className="font-bold text-2xl text-gray-800">{subject}</span>
      </Heading>
    </Section>
  );
}

function Footer({ unsubscribeURL }: { unsubscribeURL?: string | false }) {
  return (
    <Section className="mt-8 border-gray-200 border-t pt-6">
      {unsubscribeURL && (
        <Text className="my-2 text-center text-light text-xs">
          You're receiving this email because you signed up for an account at{" "}
          <Link
            href={import.meta.env.VITE_APP_URL}
            className="text-light underline"
          >
            cite.me.in
          </Link>
          <br />
          <Link href={unsubscribeURL} className="text-primary underline">
            Unsubscribe from all emails
          </Link>
        </Text>
      )}

      <Text className="my-2 text-center text-light text-sm leading-relaxed">
        <Link
          href={new URL("/privacy", import.meta.env.VITE_APP_URL).toString()}
          className="text-primary underline"
        >
          Privacy Policy
        </Link>{" "}
        •{" "}
        <Link
          href={new URL("/terms", import.meta.env.VITE_APP_URL).toString()}
          className="text-primary underline"
        >
          Terms of Service
        </Link>
      </Text>

      <Text className="my-2 text-center text-light text-xs">
        Squirrel-brain friendly 🐿️
      </Text>
    </Section>
  );
}
