import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Preview,
  Row,
  Section,
  Tailwind,
  Text,
  pixelBasedPreset,
} from "react-email";
import { EmailLinkContext } from "~/components/email/context";
import Link from "~/components/email/Link";
import envVars from "~/lib/envVars.server";
import generateUnsubscribeToken from "./generateUnsubscribeToken";

/**
 * EmailLayout is a component that wraps the email content and provides a consistent layout.
 * It is used to ensure that all emails have the same layout and consistent styling.
 *
 * @param children - The content of the email.
 * @param preview - The preview text of the email. If not provided, the subject will be used.
 * @param subject - The subject of the email.
 * @param unsubscribeURL - The URL to unsubscribe from all emails.
 * @returns The HTML email.
 */
export default function EmailLayout({
  children,
  domain,
  preview,
  subject,
  unsubscribeURL,
  user,
}: {
  children: React.ReactNode;
  domain?: string;
  preview?: string;
  subject: string;
  unsubscribeURL?: string | false;
  user: { email: string };
}) {
  const token = generateUnsubscribeToken(user.email);

  return (
    <EmailLinkContext.Provider value={{ email: user.email, token }}>
      <Html>
        <Head />
        <Preview>{preview ?? subject}</Preview>
        <Tailwind
          config={{
            presets: [pixelBasedPreset],
            theme: {
              extend: {
                colors: {
                  primary: "#4f46e5",
                  text: "#374151",
                  dark: "#1f2937",
                  light: "#6b7280",
                  background: "#f6f9fc",
                  white: "#ffffff",
                  highlightBg: "#f3f4f6",
                  border: "#e5e7eb",
                  borderLight: "#f0f0f0",
                },
              },
            },
          }}
        >
          <Body className="bg-background text-text font-sans">
            <Container className="my-40px max-w-600px mx-auto bg-white p-4">
              <Header domain={domain} subject={subject} />
              {children}
              <Footer unsubscribeURL={unsubscribeURL} />
            </Container>
          </Body>
        </Tailwind>
      </Html>
    </EmailLinkContext.Provider>
  );
}

function Header({ domain, subject }: { domain?: string; subject: string }) {
  const logoSrc = new URL("/icon-192.png", envVars.VITE_APP_URL).toString();

  return domain ? (
    <Section className="border-border mb-6 border-b pb-6">
      <Row>
        <Column style={{ verticalAlign: "middle" }}>
          <Row>
            <Column style={{ width: "44px", verticalAlign: "middle" }}>
              <Img alt="cite.me.in" height={36} src={logoSrc} width={36} />
            </Column>
            <Column style={{ verticalAlign: "middle" }}>
              <Link
                href={new URL(
                  `/site/${domain}`,
                  envVars.VITE_APP_URL,
                ).toString()}
              >
                <Text className="text-dark m-0 line-clamp-1 text-2xl leading-tight font-bold">
                  {domain}
                </Text>
                <Text className="mt-4px text-light m-0 line-clamp-1 text-sm">
                  {subject}
                </Text>
              </Link>
            </Column>
          </Row>
        </Column>
        <Column
          className="text-right"
          style={{ verticalAlign: "middle", whiteSpace: "nowrap" }}
        >
          <Text className="text-light m-0 text-sm">
            ⚡ Generated by{" "}
            <Link href={envVars.VITE_APP_URL}>
              <strong className="text-dark">cite.me.in</strong>
            </Link>
          </Text>
        </Column>
      </Row>
    </Section>
  ) : (
    <Section>
      <Heading className="my-6 flex items-center justify-center gap-2 text-center whitespace-nowrap">
        <Img alt="cite.me.in" height={32} src={logoSrc} width={32} />
        <span className="text-2xl font-bold text-gray-800">{subject}</span>
      </Heading>
    </Section>
  );
}

function Footer({ unsubscribeURL }: { unsubscribeURL?: string | false }) {
  return (
    <Section className="mt-8 border-t border-gray-200 pt-6">
      {unsubscribeURL && (
        <Text className="text-light my-2 text-center text-xs">
          You're receiving this email because you signed up for an account at{" "}
          <Link href={envVars.VITE_APP_URL} className="text-light underline">
            cite.me.in
          </Link>
          <br />
          <Link href={unsubscribeURL} className="text-primary underline">
            Unsubscribe from all emails
          </Link>
        </Text>
      )}

      <Text className="text-light my-2 text-center text-sm leading-relaxed">
        <Link
          href={new URL("/privacy", envVars.VITE_APP_URL).toString()}
          className="text-primary underline"
        >
          Privacy Policy
        </Link>{" "}
        •{" "}
        <Link
          href={new URL("/terms", envVars.VITE_APP_URL).toString()}
          className="text-primary underline"
        >
          Terms of Service
        </Link>
      </Text>

      <Text className="text-light my-2 text-center text-xs">
        Squirrel-brain friendly 🐿️
      </Text>
    </Section>
  );
}
