#!/usr/bin/env bash

# Deploy the application to the production environment. This will run the tests,
# generate the types, update the database, and deploy to Vercel. This always
# deploys to production and does not require promotion, so use with care.
#
# Usage:
#   scripts/deploy.ts

set -eo pipefail

echo -e "\033[32m  Checking code is clean …\033[0m"
pnpm check

echo -e "\033[32m  Installing Playwright …\033[0m"
pnpm exec playwright install

echo -e "\033[32m  Running tests …\033[0m"
NODE_OPTIONS="--max-old-space-size=3096" vp test run

echo -e "\033[32m  Running Playwright tests …\033[0m"
NODE_OPTIONS="--max-old-space-size=3096" playwright test

echo -e "\033[32m  Updating database …\033[0m"
infisical --env prod run -- pnpm prisma db push

echo -e "\033[32m  Deploying to Vercel …\033[0m"
set $PATH=node_modules/.bin:$PATH
vercel pull --environment=production
vercel build 
vercel deploy --prebuilt > deploy.log

echo -e "\033[32m  Opening deployment URL …\033[0m"
open $(cat deploy.log)
