name: Deploy

on:
  - push
  - workflow_dispatch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  NODE_OPTIONS: "--max-old-space-size=3096"
  POSTGRES_URL_NON_POOLING: "postgresql://postgres:postgres@localhost:5432/citeup_test"
  POSTGRES_URL: "postgresql://postgres:postgres@localhost:5432/citeup_test?pgbouncer=true"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: citeup_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Cache NPM dependencies
        id: cache-npm
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install NPM dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Set PLAYWRIGHT_VERSION
        run: echo "PLAYWRIGHT_VERSION=$(pnpm exec playwright --version)" >> $GITHUB_ENV

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright (Chromium)
        timeout-minutes: 5
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      - name: Setup database schema for testing
        run: |
          pnpm prisma generate 
          pnpm prisma db push

      - name: Check secrets
        run: pnpm secretlint "**/*" --format stylish

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Lint code
        run: biome lint

      - name: Generate React Router types
        run: pnpm react-router typegen

      - name: Check types
        run: pnpm tsc --noEmit --strict

      - uses: Infisical/secrets-action@v1.0.15
        with:
          method: "universal"
          identity-id: "2558782e-875b-4c3b-b40a-6d405dadffe0"
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          domain: "https://app.infisical.com"
          env-slug: "dev"
          project-slug: "cite-me-in"
          export-type: "file"
          file-output-path: "/.env"

      - name: Run Tests
        run: pnpm --expose-gc vitest run

      - name: Run Playwright Tests
        if: github.ref == 'refs/heads/not-main'
        run: pnpm playwright test

      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v7
        continue-on-error: true
        with:
          name: playwright-test-results
          path: __screenshots__

      - uses: Infisical/secrets-action@v1.0.15
        with:
          method: "universal"
          identity-id: "2558782e-875b-4c3b-b40a-6d405dadffe0"
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          domain: "https://app.infisical.com"
          env-slug: "prod"
          project-slug: "cite-me-in"

      - name: Update database
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm prisma db push

      - name: Deploy to Vercel
        uses: nexterias/actions-vercel@v1
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          prebuilt: false
          production: false
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          token: ${{ secrets.VERCEl_TOKEN }}
