name: Test Docker Push

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Set up pnpm and Node.js
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: Infisical/secrets-action@v1.0.15
        with:
          method: "universal"
          identity-id: "2558782e-875b-4c3b-b40a-6d405dadffe0"
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          domain: "https://app.infisical.com"
          env-slug: "dev"
          project-slug: "cite-me-in"
          export-type: "file"
          file-output-path: ".env"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-permissions
          secrets: |
            infisical_token=${{ secrets.INFISICAL_TOKEN }}
          build-args: |
            INFISICAL_ENV=dev
